# Generated by Django 3.1.1 on 2021-10-26 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=188, unique=True)),
                ('p_description', models.CharField(max_length=1000)),
                ('p_creator', models.CharField(max_length=100)),
                ('p_tester', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RunEnv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=188, unique=True)),
                ('host_url', models.CharField(max_length=1000, unique=True)),
                ('env_description', models.CharField(max_length=1000)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auto_test.project')),
            ],
        ),
        migrations.CreateModel(
            name='MoKuai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('m_description', models.CharField(max_length=200)),
                ('m_creator', models.CharField(max_length=100)),
                ('m_tester', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auto_test.project')),
            ],
            options={
                'verbose_name': 'model',
                'verbose_name_plural': 'models',
            },
        ),
        migrations.CreateModel(
            name='CaseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=188, unique=True)),
                ('url', models.CharField(max_length=10000)),
                ('method', models.CharField(max_length=20)),
                ('re_header', models.TextField()),
                ('param_type', models.CharField(max_length=15)),
                ('params', models.CharField(max_length=10000)),
                ('check', models.CharField(max_length=1000)),
                ('check_type', models.CharField(max_length=15)),
                ('case_description', models.TextField(blank=True)),
                ('result', models.BooleanField(blank=True, null=True)),
                ('creator', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('execution_time', models.DateTimeField()),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auto_test.mokuai')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auto_test.project')),
                ('suite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auto_test.testsuite')),
            ],
        ),
    ]
