# Generated by Django 3.1.1 on 2021-11-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='p_description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
