# Generated by Django 3.1.1 on 2021-11-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test', '0003_auto_20211116_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runenv',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='runenv',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
