# Generated by Django 3.1.1 on 2021-11-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test', '0004_auto_20211116_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caselist',
            name='execution_time',
        ),
        migrations.RemoveField(
            model_name='caselist',
            name='result',
        ),
        migrations.AddField(
            model_name='caselist',
            name='status',
            field=models.BooleanField(default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='caselist',
            name='check',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='caselist',
            name='params',
            field=models.TextField(),
        ),
    ]
