# Generated by Django 3.1.1 on 2021-12-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test', '0006_auto_20211208_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caselist',
            name='case_description',
        ),
    ]
