# Generated by Django 3.1.1 on 2021-12-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test', '0007_remove_caselist_case_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caselist',
            name='check',
        ),
        migrations.AddField(
            model_name='caselist',
            name='assert_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='caselist',
            name='check_key',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='caselist',
            name='check_value',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
