# Generated by Django 3.1.1 on 2021-12-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test', '0008_auto_20211220_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caselist',
            name='re_header',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
