# Generated by Django 3.1.1 on 2022-01-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test', '0009_auto_20211224_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='caselist',
            name='var_rules',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='caselist',
            name='variable',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
