# Generated by Django 3.1.1 on 2021-07-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, unique=True)),
                ('api_name', models.CharField(max_length=100, unique=True)),
                ('url', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=15)),
                ('headers', models.CharField(blank=True, max_length=400)),
                ('params', models.CharField(blank=True, max_length=1000)),
                ('params_type', models.CharField(blank=True, max_length=20)),
                ('judge', models.CharField(blank=True, max_length=200)),
                ('judge_type', models.CharField(blank=True, max_length=30)),
                ('case_description', models.TextField(blank=True, max_length=300)),
                ('creator', models.CharField(default='无名', max_length=50)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'm_api',
            },
        ),
    ]
